/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('primevue/button')['default']
    CustomTransition: (typeof import("./src/ui/UiTransition/CustomTransition.vue"))["default"]
    FadeTransition: (typeof import("./src/ui/UiTransition/components/FadeTransition/FadeTransition.vue"))["default"]
    InputSwitch: (typeof import("primevue/inputswitch"))["default"]
    MainHeader: (typeof import("./src/layouts/MainLayout/components/MainHeader.vue"))["default"]
    MainSidebar: (typeof import("./src/layouts/MainLayout/components/MainSidebar.vue"))["default"]
    MobileSidebar: (typeof import("./src/layouts/MainLayout/components/MobileSidebar.vue"))["default"]
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('primevue/sidebar')['default']
    SidebarContent: typeof import('./src/components/SidebarContent/SidebarContent.vue')['default']
    SlideInTransition: (typeof import("./src/ui/UiTransition/components/SlideInTransition/SlideInTransition.vue"))["default"]
  }
}
